"""Queue contract for trusted log events."""

from typing import Protocol

from app.domain.logs import LogEvent


class EventQueue(Protocol):
    async def publish(self, event: LogEvent) -> None: ...
    async def consume(self) -> LogEvent: ...
    def task_done(self) -> None: ...
    async def join(self) -> None: ...
